// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBWTjbVRcx7vqwZ0aC01bvWJ66-i0jVmw',
    appId: '1:907458222644:web:57e77575e23911a4fe8861',
    messagingSenderId: '907458222644',
    projectId: 'appguardanoturno',
    authDomain: 'appguardanoturno.firebaseapp.com',
    storageBucket: 'appguardanoturno.firebasestorage.app',
    measurementId: 'G-GK1CB9T2BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSFeUjhRhYKuvPOdR2XN3bahyZp4rDw4c',
    appId: '1:907458222644:android:dc1eb48e6e9c20e2fe8861',
    messagingSenderId: '907458222644',
    projectId: 'appguardanoturno',
    storageBucket: 'appguardanoturno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-noRAgGXiyX6l-da5I2-4SMoaqR-_964',
    appId: '1:907458222644:ios:611fe2b7b413512efe8861',
    messagingSenderId: '907458222644',
    projectId: 'appguardanoturno',
    storageBucket: 'appguardanoturno.firebasestorage.app',
    iosBundleId: 'com.example.appGuarda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-noRAgGXiyX6l-da5I2-4SMoaqR-_964',
    appId: '1:907458222644:ios:611fe2b7b413512efe8861',
    messagingSenderId: '907458222644',
    projectId: 'appguardanoturno',
    storageBucket: 'appguardanoturno.firebasestorage.app',
    iosBundleId: 'com.example.appGuarda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBWTjbVRcx7vqwZ0aC01bvWJ66-i0jVmw',
    appId: '1:907458222644:web:d92284c0dc869823fe8861',
    messagingSenderId: '907458222644',
    projectId: 'appguardanoturno',
    authDomain: 'appguardanoturno.firebaseapp.com',
    storageBucket: 'appguardanoturno.firebasestorage.app',
    measurementId: 'G-SH3MMES3DL',
  );
}
